auto: true
watch: true
server: true
server_port: 4001
pygments: true
paginate: 10
permalink: /:year/:month/:title/

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
#lsi:         true
pygments:    false
markdown:    maruku
safe:        false
sass:        false